# Generated by Django 6.0.1 on 2026-01-28 20:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TirePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_id', models.CharField(max_length=50, unique=True)),
                ('brand_name', models.CharField(max_length=100)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('initial_tread_depth', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discarding_tread_depth', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ideal_pressure', models.PositiveIntegerField(help_text='Standard PSI')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('vehicle_type', models.CharField(max_length=50)),
                ('odometer', models.PositiveIntegerField()),
                ('num_op_tires', models.PositiveIntegerField(default=10, verbose_name='Operational Tires')),
                ('num_sp_tires', models.PositiveIntegerField(default=1, verbose_name='Spare Tires')),
            ],
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_tread_depth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tires.tirestatus')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tires.supplier')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tires.tirepattern')),
            ],
        ),
    ]
