# Generated by Django 6.0.1 on 2026-01-28 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0002_tirepattern_vehicle_tire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tirepattern',
            name='pattern_id',
        ),
        migrations.AddField(
            model_name='tirepattern',
            name='axle_type',
            field=models.CharField(choices=[('S', 'Steer'), ('D', 'Drive'), ('T', 'Trailer'), ('A', 'All-Position')], default='S', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tirepattern',
            name='load_index',
            field=models.IntegerField(default=69, help_text='e.g., 152'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tirepattern',
            name='pattern_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tirepattern',
            name='road_type',
            field=models.CharField(choices=[('H', 'Highway'), ('R', 'Regional'), ('U', 'Urban'), ('O', 'Off-Road')], default='H', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tirepattern',
            name='speed_symbol',
            field=models.CharField(default='L', help_text='e.g., L, M, or K', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.TextField(default='good'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tirepattern',
            name='discarding_tread_depth',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tirepattern',
            name='ideal_pressure',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tirepattern',
            name='initial_tread_depth',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.CreateModel(
            name='TirePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50)),
                ('axle_type', models.CharField(max_length=20)),
                ('tire_order', models.IntegerField(unique=True)),
                ('is_spare', models.BooleanField(default=False)),
                ('mounted_tire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tires.tire')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tires.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TireInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_odometer', models.PositiveIntegerField()),
                ('inspection_date', models.DateField()),
                ('tread_depth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pressure', models.IntegerField()),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tires.employee')),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tires.tire')),
                ('wear_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tires.weartype')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tires.tireposition')),
            ],
        ),
        migrations.CreateModel(
            name='TireAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateTimeField(auto_now_add=True)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('start_odometer', models.PositiveIntegerField()),
                ('end_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('removal_mileage', models.PositiveIntegerField()),
                ('reason_for_removal', models.TextField(blank=True)),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tires.tire')),
                ('from_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_from', to='tires.tireposition')),
                ('to_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_to', to='tires.tireposition')),
            ],
        ),
    ]
