# Generated by Django 6.0.1 on 2026-01-28 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0003_remove_tirepattern_pattern_id_tirepattern_axle_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='tireinspection',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tires.tireposition'),
        ),
        migrations.CreateModel(
            name='Maintainance_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_mileage', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField()),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tires.employee')),
                ('tire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tires.tire')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tires.service_type')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_id', models.CharField(max_length=50, unique=True, verbose_name='Work Order ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('current_odometer', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shift_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('O', 'OPENED'), ('P', 'PENDING'), ('C', 'CLOSED')], max_length=1)),
                ('notes', models.TextField()),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_employee', to='tires.employee')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver', to='tires.employee')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tires.vehicle')),
            ],
        ),
    ]
