# Generated by Django 6.0.1 on 2026-01-30 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0004_service_type_alter_tireinspection_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='date_closed',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='shift_type',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='wo_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='position',
            field=models.TextField(default='Manager'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tire',
            name='current_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tires.tireposition'),
        ),
        migrations.AddField(
            model_name='tire',
            name='max_retreads',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tire',
            name='retread_count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tire',
            name='size',
            field=models.TextField(default=67),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tire',
            name='tire_mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tireassignment',
            name='work_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tires.workorder'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tire_configuration',
            field=models.TextField(default='3x3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintainance_record',
            name='tire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_history', to='tires.tire'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tire',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tires.tirepattern'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tire',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tires.supplier'),
        ),
        migrations.AlterField(
            model_name='tireassignment',
            name='end_odometer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_wo', to='tires.workorder'),
        ),
        migrations.AlterField(
            model_name='tireassignment',
            name='removal_mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tireassignment',
            name='start_odometer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_wo', to='tires.workorder'),
        ),
        migrations.AlterField(
            model_name='tireinspection',
            name='inspection_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tireinspection',
            name='inspection_odometer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tires.workorder'),
        ),
        migrations.AlterField(
            model_name='tireinspection',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tires.employee'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_employee', to='tires.employee'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='tires.employee'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
