# Generated by Django 6.0.1 on 2026-01-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0005_remove_workorder_date_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='current_pressure',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tireinspection',
            name='inspection_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
