# Generated by Django 6.0.1 on 2026-01-30 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0006_tire_current_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tireassignment',
            name='from_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_from', to='tires.tireposition'),
        ),
        migrations.AlterField(
            model_name='tireinspection',
            name='inspection_date',
            field=models.DateTimeField(),
        ),
    ]
