# Generated by Django 6.0.1 on 2026-01-30 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0007_alter_tireassignment_from_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tireassignment',
            name='start_odometer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_wo', to='tires.workorder'),
        ),
        migrations.AlterField(
            model_name='tireposition',
            name='tire_order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='tireposition',
            unique_together={('vehicle', 'tire_order')},
        ),
    ]
