# Generated by Django 6.0.1 on 2026-01-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0008_alter_tireassignment_start_odometer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='current_pressure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='current_tread_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
