# Generated by Django 6.0.1 on 2026-01-30 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0009_alter_tire_current_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tireassignment',
            name='to_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_to', to='tires.tireposition'),
        ),
    ]
