# Generated by Django 6.0.1 on 2026-02-03 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0010_alter_tireassignment_to_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tireassignment',
            name='end_odometer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_wo', to='tires.workorder'),
        ),
        migrations.AlterField(
            model_name='tirestatus',
            name='name',
            field=models.IntegerField(choices=[(1, 'New Tire'), (2, 'Mounted Tire'), (3, 'Used Tire'), (4, 'For Recycling'), (5, 'Discarded'), (6, 'Re-treaded')], default=3),
        ),
    ]
