# Generated by Django 6.0.1 on 2026-02-03 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0011_alter_tireassignment_end_odometer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tire',
            name='tire_mileage',
        ),
        migrations.RemoveField(
            model_name='tireassignment',
            name='removal_mileage',
        ),
        migrations.AlterField(
            model_name='tire',
            name='current_position',
            field=models.ForeignKey(blank=True, help_text='If null, the tire is in the warehouse.', null=True, on_delete=django.db.models.deletion.PROTECT, to='tires.tireposition'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='max_retreads',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='tire',
            name='retread_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tire',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tireassignment',
            name='end_odometer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closing_assignments', to='tires.workorder'),
        ),
        migrations.AlterField(
            model_name='tireassignment',
            name='start_odometer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_assignments', to='tires.workorder'),
        ),
    ]
