# Generated by Django 6.0.1 on 2026-02-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0012_remove_tire_tire_mileage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='tire_mileage',
            field=models.PositiveIntegerField(default=0, help_text='Total KM driven'),
        ),
    ]
