# Generated by Django 6.0.1 on 2026-02-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0013_tire_tire_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tireinspection',
            name='recorded_consumption_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tireinspection',
            name='recorded_cost_per_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tireinspection',
            name='recorded_current_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tireinspection',
            name='recorded_fuel_impact',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tireinspection',
            name='recorded_remaining_distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
