# Generated by Django 6.0.1 on 2026-02-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0014_tireinspection_recorded_consumption_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tireassignment',
            name='stint_distance',
            field=models.FloatField(default=0),
        ),
    ]
