# Generated by Django 6.0.1 on 2026-02-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0015_tireassignment_stint_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tireposition',
            name='axle_type',
            field=models.CharField(choices=[('S', 'Steer'), ('D', 'Drive'), ('T', 'Trailer'), ('A', 'All-Position')], max_length=1),
        ),
    ]
