# Generated by Django 6.0.1 on 2026-02-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0016_alter_tireposition_axle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Operational'), (2, 'Under Maintenance'), (3, 'Out Of Commission')], default=1),
        ),
    ]
